import 'package:cloud_firestore/cloud_firestore.dart';

class TopicSeed {
  static Future<void> seedTopics() async {
    final firestore = FirebaseFirestore.instance;

    final List<Map<String, dynamic>> topics = [
      // ===========================================================
      // CLASS 10 - MATHEMATICS
      // ===========================================================

      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Real Numbers",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Polynomials",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Pair of Linear Equations in Two Variables",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Quadratic Equations",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Arithmetic Progressions",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Triangles",
        "description": "",
        "order": 6,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Coordinate Geometry",
        "description": "",
        "order": 7,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Introduction to Trigonometry",
        "description": "",
        "order": 8,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Some Applications of Trigonometry",
        "description": "",
        "order": 9,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Circles",
        "description": "",
        "order": 10,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Areas Related to Circles",
        "description": "",
        "order": 11,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Surface Areas and Volumes",
        "description": "",
        "order": 12,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Statistics",
        "description": "",
        "order": 13,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Probability",
        "description": "",
        "order": 14,
      },

      // ===========================================================
      // CLASS 10 - PHYSICS
      // ===========================================================

      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Light – Reflection and Refraction",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "The Human Eye and the Colourful World",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Electricity",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Magnetic Effects of Electric Current",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Sources of Energy",
        "description": "",
        "order": 5,
      },

      // ===========================================================
      // CLASS 10 - CHEMISTRY
      // ===========================================================

      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Chemical Reactions and Equations",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Acids, Bases and Salts",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Metals and Non-metals",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Carbon and Its Compounds",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Periodic Classification of Elements",
        "description": "",
        "order": 5,
      },

      // ===========================================================
      // CLASS 10 - BIOLOGY
      // ===========================================================

      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Life Processes",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Control and Coordination",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "How Do Organisms Reproduce?",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Heredity and Evolution",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Our Environment",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class10",
        "className": "Class 10",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Sustainable Management of Natural Resources",
        "description": "",
        "order": 6,
      },

      // ============================
      // CLASS 11 STARTS IN PART 2
      // ============================

            // ===========================================================
      // CLASS 11 - MATHEMATICS
      // ===========================================================

      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Sets",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Relations and Functions",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Trigonometric Functions",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Principle of Mathematical Induction",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Complex Numbers and Quadratic Equations",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Linear Inequalities",
        "description": "",
        "order": 6,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Permutations and Combinations",
        "description": "",
        "order": 7,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Binomial Theorem",
        "description": "",
        "order": 8,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Sequences and Series",
        "description": "",
        "order": 9,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Straight Lines",
        "description": "",
        "order": 10,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Conic Sections",
        "description": "",
        "order": 11,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Introduction to Three Dimensional Geometry",
        "description": "",
        "order": 12,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Limits and Derivatives",
        "description": "",
        "order": 13,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Mathematical Reasoning",
        "description": "",
        "order": 14,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Statistics",
        "description": "",
        "order": 15,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Probability",
        "description": "",
        "order": 16,
      },

      // ===========================================================
      // CLASS 11 - PHYSICS
      // ===========================================================

      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Physical World",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Units and Measurements",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Motion in a Straight Line",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Motion in a Plane",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Laws of Motion",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Work, Energy and Power",
        "description": "",
        "order": 6,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "System of Particles and Rotational Motion",
        "description": "",
        "order": 7,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Gravitation",
        "description": "",
        "order": 8,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Mechanical Properties of Solids",
        "description": "",
        "order": 9,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Mechanical Properties of Fluids",
        "description": "",
        "order": 10,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Thermal Properties of Matter",
        "description": "",
        "order": 11,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Thermodynamics",
        "description": "",
        "order": 12,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Kinetic Theory",
        "description": "",
        "order": 13,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Oscillations",
        "description": "",
        "order": 14,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Waves",
        "description": "",
        "order": 15,
      },

      // ===========================================================
  
      // ===========================================================
      // CLASS 11 - CHEMISTRY
      // ===========================================================

      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Some Basic Concepts of Chemistry",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Structure of Atom",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Classification of Elements and Periodicity in Properties",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Chemical Bonding and Molecular Structure",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "States of Matter",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Thermodynamics",
        "description": "",
        "order": 6,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Equilibrium",
        "description": "",
        "order": 7,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Redox Reactions",
        "description": "",
        "order": 8,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Hydrogen",
        "description": "",
        "order": 9,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "The s-Block Elements",
        "description": "",
        "order": 10,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "The p-Block Elements",
        "description": "",
        "order": 11,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Organic Chemistry - Some Basic Principles and Techniques",
        "description": "",
        "order": 12,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Hydrocarbons",
        "description": "",
        "order": 13,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Environmental Chemistry",
        "description": "",
        "order": 14,
      },

      // ===========================================================
      // CLASS 11 - BIOLOGY
      // ===========================================================

      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "The Living World",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Biological Classification",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Plant Kingdom",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Animal Kingdom",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Morphology of Flowering Plants",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Anatomy of Flowering Plants",
        "description": "",
        "order": 6,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Structural Organisation in Animals",
        "description": "",
        "order": 7,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Cell: The Unit of Life",
        "description": "",
        "order": 8,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Biomolecules",
        "description": "",
        "order": 9,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Cell Cycle and Cell Division",
        "description": "",
        "order": 10,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Transport in Plants",
        "description": "",
        "order": 11,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Mineral Nutrition",
        "description": "",
        "order": 12,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Photosynthesis in Higher Plants",
        "description": "",
        "order": 13,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Respiration in Plants",
        "description": "",
        "order": 14,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Plant Growth and Development",
        "description": "",
        "order": 15,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Digestion and Absorption",
        "description": "",
        "order": 16,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Breathing and Exchange of Gases",
        "description": "",
        "order": 17,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Body Fluids and Circulation",
        "description": "",
        "order": 18,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Excretory Products and Their Elimination",
        "description": "",
        "order": 19,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Locomotion and Movement",
        "description": "",
        "order": 20,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Neural Control and Coordination",
        "description": "",
        "order": 21,
      },
      {
        "classId": "class11",
        "className": "Class 11",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Chemical Coordination and Integration",
        "description": "",
        "order": 22,
      },

      // ===========================================================
      // CLASS 12 STARTS IN PART 4
      // ===========================================================

            // ===========================================================
      // CLASS 12 - MATHEMATICS
      // ===========================================================

      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Relations and Functions",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Inverse Trigonometric Functions",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Matrices",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Determinants",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Continuity and Differentiability",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Applications of Derivatives",
        "description": "",
        "order": 6,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Integrals",
        "description": "",
        "order": 7,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Applications of Integrals",
        "description": "",
        "order": 8,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Differential Equations",
        "description": "",
        "order": 9,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Vector Algebra",
        "description": "",
        "order": 10,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Three Dimensional Geometry",
        "description": "",
        "order": 11,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Linear Programming",
        "description": "",
        "order": 12,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "math",
        "subjectName": "Mathematics",
        "title": "Probability",
        "description": "",
        "order": 13,
      },

      // ===========================================================
      // CLASS 12 - PHYSICS
      // ===========================================================

      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Electric Charges and Fields",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Electrostatic Potential and Capacitance",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Current Electricity",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Moving Charges and Magnetism",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Magnetism and Matter",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Electromagnetic Induction",
        "description": "",
        "order": 6,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Alternating Current",
        "description": "",
        "order": 7,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Electromagnetic Waves",
        "description": "",
        "order": 8,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Ray Optics and Optical Instruments",
        "description": "",
        "order": 9,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Wave Optics",
        "description": "",
        "order": 10,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Dual Nature of Radiation and Matter",
        "description": "",
        "order": 11,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Atoms",
        "description": "",
        "order": 12,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Nuclei",
        "description": "",
        "order": 13,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Semiconductor Electronics",
        "description": "",
        "order": 14,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "physics",
        "subjectName": "Physics",
        "title": "Communication Systems",
        "description": "",
        "order": 15,
      },

      // ===========================================================
      // CLASS 12 CHEMISTRY STARTS IN PART 5
      // ===========================================================
            // ===========================================================
      // CLASS 12 - CHEMISTRY
      // ===========================================================

      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Solutions",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Electrochemistry",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Chemical Kinetics",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "d- and f-Block Elements",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Coordination Compounds",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Haloalkanes and Haloarenes",
        "description": "",
        "order": 6,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Alcohols, Phenols and Ethers",
        "description": "",
        "order": 7,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Aldehydes, Ketones and Carboxylic Acids",
        "description": "",
        "order": 8,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Amines",
        "description": "",
        "order": 9,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "chemistry",
        "subjectName": "Chemistry",
        "title": "Biomolecules",
        "description": "",
        "order": 10,
      },

      // ===========================================================
      // CLASS 12 - BIOLOGY
      // ===========================================================

      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Sexual Reproduction in Flowering Plants",
        "description": "",
        "order": 1,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Human Reproduction",
        "description": "",
        "order": 2,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Reproductive Health",
        "description": "",
        "order": 3,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Principles of Inheritance and Variation",
        "description": "",
        "order": 4,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Molecular Basis of Inheritance",
        "description": "",
        "order": 5,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Evolution",
        "description": "",
        "order": 6,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Human Health and Disease",
        "description": "",
        "order": 7,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Microbes in Human Welfare",
        "description": "",
        "order": 8,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Biotechnology - Principles and Processes",
        "description": "",
        "order": 9,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Biotechnology and its Applications",
        "description": "",
        "order": 10,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Organisms and Populations",
        "description": "",
        "order": 11,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Ecosystem",
        "description": "",
        "order": 12,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Biodiversity and Conservation",
        "description": "",
        "order": 13,
      },
      {
        "classId": "class12",
        "className": "Class 12",
        "subjectId": "biology",
        "subjectName": "Biology",
        "title": "Environmental Issues",
        "description": "",
        "order": 14,
      },

      // ===========================================================
      // FIRESTORE INSERTION LOOP STARTS IN PART 6
      // ===========================================================
          ];

    final batch = firestore.batch();

    for (final topic in topics) {
      final query = await firestore
          .collection('topics')
          .where('classId', isEqualTo: topic['classId'])
          .where('subjectId', isEqualTo: topic['subjectId'])
          .where('title', isEqualTo: topic['title'])
          .limit(1)
          .get();

      if (query.docs.isEmpty) {
        final docRef = firestore.collection('topics').doc();

        batch.set(docRef, {
          ...topic,
          "estimatedDuration": 60,
          "isActive": true,
          "createdAt": FieldValue.serverTimestamp(),
        });
      }
    }

    await batch.commit();

    print("========================================");
    print("NCERT Topics Imported Successfully");
    print("Total Topics : ${topics.length}");
    print("========================================");
  }
}